import 'package:local_service_providers/model/categories.dart';

var menuItems = [
  "Applience Repair Service",
  "Cleaning Services",
  "Electricians",
  "Pest Control Services",
  "Carpenter",
  "Animal Rescue",
  "Plumbers",
  "Countertop Services",
  "Business Lawyer Service",
  "GarageDoo",
  "Junk Removel Service",
  "Landscaping Service",
  "ChildCare",
  "Fencing Service",
  "Autoglass Services",
  "Car Repair",
  "Event Planner",
  "Home Dust Cleaner",
  "Food Maker",
];

const availabelCategories = [
  Category(title: "Applience Repair Service"),
  Category(title: "Cleaning Services"),
  Category(title: "Electricians"),
  Category(title: "Pest Control Services"),
  Category(title: "Carpenter"),
  Category(title: "Animal Rescue"),
  Category(title: "Plumbers"),
  Category(title: "Countertop Services"),
  Category(title: "GarageDoo"),
  Category(title: "Junk Removel Service"),
  Category(title: "Landscaping Service"),
  Category(title: "ChildCare"),
  Category(title: "Fencing Service"),
  Category(title: "Autoglass Services"),
  Category(title: "Car Repair"),
  Category(title: "Event Planner"),
  Category(title: "Home Dust Cleaner"),
  Category(title: "Food Makerr"),
];
